# Generated by Django 3.2.8 on 2021-10-29 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_name', models.CharField(max_length=100)),
                ('emp_age', models.CharField(max_length=100)),
                ('emp_sex', models.CharField(max_length=100)),
                ('emp_department', models.CharField(max_length=100)),
                ('emp_title', models.CharField(max_length=100)),
                ('emp_salary', models.CharField(max_length=100)),
            ],
        ),
    ]
