# Generated by Django 3.2.8 on 2021-10-29 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='emp_age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='employees',
            name='emp_salary',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
