# Generated by Django 3.2.8 on 2021-10-29 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0002_auto_20211029_0938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='emp_age',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='employees',
            name='emp_salary',
            field=models.CharField(max_length=100),
        ),
    ]
