# Generated by Django 3.2.8 on 2021-10-29 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0003_auto_20211029_0951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='emp_age',
            field=models.IntegerField(max_length=100),
        ),
        migrations.AlterField(
            model_name='employees',
            name='emp_salary',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
