# Generated by Django 3.2.8 on 2021-10-29 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0004_auto_20211029_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='emp_age',
            field=models.IntegerField(),
        ),
    ]
