# Generated by Django 3.2.8 on 2021-10-29 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0005_alter_employees_emp_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='emp_salary',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
